// Generated by scripts/build-audio.py — do not edit by hand.
// Loops: play [loopStart, loopEnd] (s); the file wraps extra audio round both ends.
// Sprites: slots are [start, duration] (s) inside the file.
export const AUDIO = {
  "stream": {
    "url": "/audio/stream.mp3",
    "loopStart": 1.0,
    "loopEnd": 21.0
  },
  "wind": {
    "url": "/audio/wind.mp3",
    "loopStart": 1.0,
    "loopEnd": 23.0
  },
  "steps": {
    "url": "/audio/steps.mp3",
    "slots": {
      "grass": [
        [0.12, 0.3273],
        [0.5673, 0.2026],
        [0.8899, 0.2924],
        [1.3023, 0.3473],
        [1.7695, 0.2674],
        [2.157, 0.2575]
      ],
      "wood": [
        [2.5344, 0.1527],
        [2.8071, 0.1178],
        [3.0449, 0.1278],
        [3.2927, 0.1427],
        [3.5554, 0.1727],
        [3.848, 0.1228]
      ],
      "stone": [
        [4.0908, 0.2369],
        [4.4477, 0.2605],
        [4.8282, 0.2402],
        [5.1884, 0.262],
        [5.5704, 0.2874],
        [5.9778, 0.2545]
      ],
      "water": [
        [6.3523, 0.393],
        [6.8653, 0.37],
        [7.3553, 0.408],
        [7.8833, 0.48],
        [8.4833, 0.44],
        [9.0433, 0.47]
      ]
    }
  },
  "birds": {
    "url": "/audio/birds.mp3",
    "slots": {
      "song": [
        [0.15, 0.9659],
        [1.2659, 0.953],
        [2.3689, 2.3477],
        [4.8666, 1.65],
        [6.6666, 0.5368],
        [7.3534, 1.2652]
      ]
    }
  },
  "ui": {
    "url": "/audio/ui.mp3",
    "slots": {
      "chime": [
        [0.12, 0.9089]
      ],
      "sparkle": [
        [1.1489, 0.38]
      ],
      "doorOpen": [
        [1.6489, 0.919]
      ],
      "doorClose": [
        [2.6878, 0.5368]
      ],
      "curtain": [
        [3.3447, 0.5917]
      ]
    }
  }
} as const;

export type SpriteKey = 'steps' | 'birds' | 'ui';
