// Generated by scripts/build-audio.py — do not edit by hand.
// Loops: play [loopStart, loopEnd] (s); the file wraps extra audio round both ends.
// Sprites: slots are [start, duration] (s) inside the file.
export const AUDIO = {
  "stream": {
    "url": "/audio/stream.mp3",
    "loopStart": 1.0,
    "loopEnd": 21.0
  },
  "wind": {
    "url": "/audio/wind.mp3",
    "loopStart": 1.0,
    "loopEnd": 23.0
  },
  "steps": {
    "url": "/audio/steps.mp3",
    "slots": {
      "grass": [
        [0.12, 0.3273],
        [0.5673, 0.2026],
        [0.8899, 0.2924],
        [1.3023, 0.3473],
        [1.7695, 0.2674],
        [2.157, 0.2575]
      ],
      "wood": [
        [2.5344, 0.1527],
        [2.8071, 0.1178],
        [3.0449, 0.1278],
        [3.2927, 0.1427],
        [3.5554, 0.1727],
        [3.848, 0.1228]
      ],
      "stone": [
        [4.0908, 0.2369],
        [4.4477, 0.2605],
        [4.8282, 0.2402],
        [5.1884, 0.262],
        [5.5704, 0.2874],
        [5.9778, 0.2545]
      ],
      "water": [
        [6.3523, 0.393],
        [6.8653, 0.37],
        [7.3553, 0.408],
        [7.8833, 0.48],
        [8.4833, 0.44],
        [9.0433, 0.47]
      ]
    }
  },
  "birds": {
    "url": "/audio/birds.mp3",
    "slots": {
      "song": [
        [0.15, 0.9659],
        [1.2659, 0.953],
        [2.3689, 2.3477],
        [4.8666, 1.65],
        [6.6666, 0.5368],
        [7.3534, 1.2652]
      ]
    }
  },
  "ui": {
    "url": "/audio/ui.mp3",
    "slots": {
      "chime": [
        [0.12, 0.9089]
      ],
      "sparkle": [
        [1.1489, 0.38]
      ],
      "doorOpen": [
        [1.6489, 0.919]
      ],
      "doorClose": [
        [2.6878, 0.5368]
      ],
      "curtain": [
        [3.3447, 0.5917]
      ]
    }
  },
  "dog": {
    "url": "/audio/dog.mp3",
    "slots": {
      "bark": [
        [0.12, 0.5368],
        [0.7768, 0.4221],
        [1.3189, 0.7015],
        [2.1404, 0.4121],
        [2.6725, 0.2229],
        [3.0154, 0.6017]
      ],
      "sniff": [
        [3.7371, 0.563],
        [4.4201, 0.5588],
        [5.0988, 1.0606],
        [6.2795, 0.3393]
      ],
      "whistle": [
        [6.7388, 0.9559],
        [7.8146, 0.8112]
      ]
    }
  },
  "pant": {
    "url": "/audio/pant.mp3",
    "loopStart": 0.5,
    "loopEnd": 2.3
  },
  "crickets": {
    "url": "/audio/crickets.mp3",
    "loopStart": 1.0,
    "loopEnd": 15.0,
    "lazy": true
  },
  "frogs": {
    "url": "/audio/frogs.mp3",
    "loopStart": 1.0,
    "loopEnd": 13.0,
    "lazy": true
  },
  "croaks": {
    "url": "/audio/croaks.mp3",
    "slots": {
      "croak": [
        [0.12, 0.423],
        [0.663, 0.413],
        [1.1961, 0.3941],
        [1.7102, 0.3572],
        [2.1874, 0.2874],
        [2.5948, 0.43]
      ]
    },
    "lazy": true
  }
} as const;

export type SpriteKey = 'steps' | 'birds' | 'ui' | 'dog' | 'croaks';
