// Generated by scripts/build-music.py — do not edit by hand.
// Background music playlist (played in order, looping), streamed after Start with sound on.
export const MUSIC = [
  {
    "url": "/audio/music-1.mp3",
    "seconds": 176.77,
    "bytes": 2251769
  },
  {
    "url": "/audio/music-2.mp3",
    "seconds": 204.8,
    "bytes": 2614038
  }
] as const;
