// Generated by scripts/gen-icons.py build — do not edit by hand.
/** Item icons (40 files, 121.5 KB total, 96x96 WebP). */
export const ICONS: Record<string, { url: string; bytes: number }> = {
  "log": {
    "url": "/icons/log.webp",
    "bytes": 2954
  },
  "leaves": {
    "url": "/icons/leaves.webp",
    "bytes": 3534
  },
  "apple": {
    "url": "/icons/apple.webp",
    "bytes": 2752
  },
  "orange": {
    "url": "/icons/orange.webp",
    "bytes": 2884
  },
  "stone": {
    "url": "/icons/stone.webp",
    "bytes": 2740
  },
  "planks": {
    "url": "/icons/planks.webp",
    "bytes": 3216
  },
  "beam": {
    "url": "/icons/beam.webp",
    "bytes": 2900
  },
  "slab": {
    "url": "/icons/slab.webp",
    "bytes": 2212
  },
  "jute": {
    "url": "/icons/jute.webp",
    "bytes": 3294
  },
  "rope": {
    "url": "/icons/rope.webp",
    "bytes": 3736
  },
  "iron": {
    "url": "/icons/iron.webp",
    "bytes": 3294
  },
  "nails": {
    "url": "/icons/nails.webp",
    "bytes": 3840
  },
  "tulip-red": {
    "url": "/icons/tulip-red.webp",
    "bytes": 2858
  },
  "tulip-pink": {
    "url": "/icons/tulip-pink.webp",
    "bytes": 2920
  },
  "tulip-yellow": {
    "url": "/icons/tulip-yellow.webp",
    "bytes": 2980
  },
  "tulip-white": {
    "url": "/icons/tulip-white.webp",
    "bytes": 3004
  },
  "tulip-orange": {
    "url": "/icons/tulip-orange.webp",
    "bytes": 2910
  },
  "tulip-purple": {
    "url": "/icons/tulip-purple.webp",
    "bytes": 2920
  },
  "tulip-blue": {
    "url": "/icons/tulip-blue.webp",
    "bytes": 2928
  },
  "cosmos-red": {
    "url": "/icons/cosmos-red.webp",
    "bytes": 3196
  },
  "cosmos-pink": {
    "url": "/icons/cosmos-pink.webp",
    "bytes": 3414
  },
  "cosmos-yellow": {
    "url": "/icons/cosmos-yellow.webp",
    "bytes": 3480
  },
  "cosmos-white": {
    "url": "/icons/cosmos-white.webp",
    "bytes": 3630
  },
  "cosmos-orange": {
    "url": "/icons/cosmos-orange.webp",
    "bytes": 3368
  },
  "cosmos-purple": {
    "url": "/icons/cosmos-purple.webp",
    "bytes": 3422
  },
  "cosmos-blue": {
    "url": "/icons/cosmos-blue.webp",
    "bytes": 3554
  },
  "pansy-red": {
    "url": "/icons/pansy-red.webp",
    "bytes": 2736
  },
  "pansy-pink": {
    "url": "/icons/pansy-pink.webp",
    "bytes": 2864
  },
  "pansy-yellow": {
    "url": "/icons/pansy-yellow.webp",
    "bytes": 2962
  },
  "pansy-white": {
    "url": "/icons/pansy-white.webp",
    "bytes": 3090
  },
  "pansy-orange": {
    "url": "/icons/pansy-orange.webp",
    "bytes": 2876
  },
  "pansy-purple": {
    "url": "/icons/pansy-purple.webp",
    "bytes": 2868
  },
  "pansy-blue": {
    "url": "/icons/pansy-blue.webp",
    "bytes": 2972
  },
  "paint-red": {
    "url": "/icons/paint-red.webp",
    "bytes": 2960
  },
  "paint-pink": {
    "url": "/icons/paint-pink.webp",
    "bytes": 3176
  },
  "paint-yellow": {
    "url": "/icons/paint-yellow.webp",
    "bytes": 3242
  },
  "paint-white": {
    "url": "/icons/paint-white.webp",
    "bytes": 3260
  },
  "paint-orange": {
    "url": "/icons/paint-orange.webp",
    "bytes": 3136
  },
  "paint-purple": {
    "url": "/icons/paint-purple.webp",
    "bytes": 3090
  },
  "paint-blue": {
    "url": "/icons/paint-blue.webp",
    "bytes": 3246
  }
};
export const ICON_SIZE = 96;
