// Generated by scripts/gen-icons.py build — do not edit by hand.
/** Item icons (26 files, 77.9 KB total, 96x96 WebP). */
export const ICONS: Record<string, { url: string; bytes: number }> = {
  "log": {
    "url": "/icons/log.webp",
    "bytes": 2954
  },
  "leaves": {
    "url": "/icons/leaves.webp",
    "bytes": 3534
  },
  "apple": {
    "url": "/icons/apple.webp",
    "bytes": 2752
  },
  "orange": {
    "url": "/icons/orange.webp",
    "bytes": 2884
  },
  "stone": {
    "url": "/icons/stone.webp",
    "bytes": 2740
  },
  "tulip-red": {
    "url": "/icons/tulip-red.webp",
    "bytes": 2858
  },
  "tulip-pink": {
    "url": "/icons/tulip-pink.webp",
    "bytes": 2920
  },
  "tulip-yellow": {
    "url": "/icons/tulip-yellow.webp",
    "bytes": 2980
  },
  "tulip-white": {
    "url": "/icons/tulip-white.webp",
    "bytes": 3004
  },
  "tulip-orange": {
    "url": "/icons/tulip-orange.webp",
    "bytes": 2910
  },
  "tulip-purple": {
    "url": "/icons/tulip-purple.webp",
    "bytes": 2920
  },
  "tulip-blue": {
    "url": "/icons/tulip-blue.webp",
    "bytes": 2928
  },
  "cosmos-red": {
    "url": "/icons/cosmos-red.webp",
    "bytes": 3196
  },
  "cosmos-pink": {
    "url": "/icons/cosmos-pink.webp",
    "bytes": 3414
  },
  "cosmos-yellow": {
    "url": "/icons/cosmos-yellow.webp",
    "bytes": 3480
  },
  "cosmos-white": {
    "url": "/icons/cosmos-white.webp",
    "bytes": 3630
  },
  "cosmos-orange": {
    "url": "/icons/cosmos-orange.webp",
    "bytes": 3368
  },
  "cosmos-purple": {
    "url": "/icons/cosmos-purple.webp",
    "bytes": 3422
  },
  "cosmos-blue": {
    "url": "/icons/cosmos-blue.webp",
    "bytes": 3554
  },
  "pansy-red": {
    "url": "/icons/pansy-red.webp",
    "bytes": 2736
  },
  "pansy-pink": {
    "url": "/icons/pansy-pink.webp",
    "bytes": 2864
  },
  "pansy-yellow": {
    "url": "/icons/pansy-yellow.webp",
    "bytes": 2962
  },
  "pansy-white": {
    "url": "/icons/pansy-white.webp",
    "bytes": 3090
  },
  "pansy-orange": {
    "url": "/icons/pansy-orange.webp",
    "bytes": 2876
  },
  "pansy-purple": {
    "url": "/icons/pansy-purple.webp",
    "bytes": 2868
  },
  "pansy-blue": {
    "url": "/icons/pansy-blue.webp",
    "bytes": 2972
  }
};
export const ICON_SIZE = 96;
