// Generated by scripts/build-textures.py — do not edit by hand.
// `mean` is the tile's average colour in linear space (used to keep the shader's palette).
export const TEXTURES = {
  "grass": {
    "url": "/textures/grass.webp",
    "kind": "tile",
    "mean": [
      0.2543,
      0.5111,
      0.0764
    ],
    "bytes": 75404
  },
  "dirt": {
    "url": "/textures/dirt.webp",
    "kind": "tile",
    "mean": [
      0.6824,
      0.4143,
      0.1677
    ],
    "bytes": 46562
  },
  "cobble": {
    "url": "/textures/cobble.webp",
    "kind": "tile",
    "mean": [
      0.6098,
      0.5329,
      0.3788
    ],
    "bytes": 39226
  },
  "sand": {
    "url": "/textures/sand.webp",
    "kind": "tile",
    "mean": [
      0.8385,
      0.577,
      0.2566
    ],
    "bytes": 47078
  },
  "riverbed": {
    "url": "/textures/riverbed.webp",
    "kind": "tile",
    "mean": [
      0.2164,
      0.1561,
      0.0799
    ],
    "bytes": 55398
  },
  "rock": {
    "url": "/textures/rock.webp",
    "kind": "tile",
    "mean": [
      0.6494,
      0.3493,
      0.1658
    ],
    "bytes": 17700
  },
  "water": {
    "url": "/textures/water.webp",
    "kind": "mask",
    "bytes": 60404
  },
  "paint-grain": {
    "url": "/textures/paint-grain.webp",
    "kind": "mask",
    "bytes": 32524
  },
  "leaf-broad": {
    "url": "/textures/leaf-broad.webp",
    "kind": "tint",
    "bytes": 13410
  },
  "needle": {
    "url": "/textures/needle.webp",
    "kind": "tint",
    "bytes": 20506
  },
  "leaf-single": {
    "url": "/textures/leaf-single.webp",
    "kind": "tint",
    "bytes": 4896
  },
  "grass-card": {
    "url": "/textures/grass-card.webp",
    "kind": "tint",
    "bytes": 17566
  },
  "moon": {
    "url": "/textures/moon.webp",
    "kind": "sprite",
    "bytes": 15122
  }
} as const;

export type TextureName = keyof typeof TEXTURES;
