// Generated by scripts/build-textures.py — do not edit by hand.
// `mean` is the tile's average colour in linear space (used to keep the shader's palette).
export const TEXTURES = {
  "grass": {
    "url": "/textures/grass.webp",
    "kind": "tile",
    "mean": [
      0.2543,
      0.5111,
      0.0764
    ],
    "bytes": 75404
  },
  "dirt": {
    "url": "/textures/dirt.webp",
    "kind": "tile",
    "mean": [
      0.6824,
      0.4143,
      0.1677
    ],
    "bytes": 46562
  },
  "cobble": {
    "url": "/textures/cobble.webp",
    "kind": "tile",
    "mean": [
      0.6098,
      0.5329,
      0.3788
    ],
    "bytes": 39226
  },
  "sand": {
    "url": "/textures/sand.webp",
    "kind": "tile",
    "mean": [
      0.8385,
      0.577,
      0.2566
    ],
    "bytes": 47078
  },
  "riverbed": {
    "url": "/textures/riverbed.webp",
    "kind": "tile",
    "mean": [
      0.2164,
      0.1561,
      0.0799
    ],
    "bytes": 55398
  },
  "rock": {
    "url": "/textures/rock.webp",
    "kind": "tile",
    "mean": [
      0.6494,
      0.3493,
      0.1658
    ],
    "bytes": 17700
  },
  "water": {
    "url": "/textures/water.webp",
    "kind": "mask",
    "mean": [
      0.2065,
      0.2065,
      0.2065
    ],
    "bytes": 60404
  },
  "paint-grain": {
    "url": "/textures/paint-grain.webp",
    "kind": "mask",
    "mean": [
      0.5265,
      0.5265,
      0.5265
    ],
    "bytes": 32524
  },
  "surf-wood": {
    "url": "/textures/surf-wood.webp",
    "kind": "mask",
    "mean": [
      0.5349,
      0.5349,
      0.5349
    ],
    "bytes": 76614
  },
  "surf-shingle": {
    "url": "/textures/surf-shingle.webp",
    "kind": "mask",
    "mean": [
      0.7098,
      0.7098,
      0.7098
    ],
    "bytes": 42046
  },
  "surf-plaster": {
    "url": "/textures/surf-plaster.webp",
    "kind": "mask",
    "mean": [
      0.4782,
      0.4782,
      0.4782
    ],
    "bytes": 32476
  },
  "surf-stone": {
    "url": "/textures/surf-stone.webp",
    "kind": "mask",
    "mean": [
      0.6103,
      0.6103,
      0.6103
    ],
    "bytes": 53462
  },
  "surf-brick": {
    "url": "/textures/surf-brick.webp",
    "kind": "mask",
    "mean": [
      0.6383,
      0.6383,
      0.6383
    ],
    "bytes": 66314
  },
  "surf-metal": {
    "url": "/textures/surf-metal.webp",
    "kind": "mask",
    "mean": [
      0.3642,
      0.3642,
      0.3642
    ],
    "bytes": 26542
  },
  "surf-canvas": {
    "url": "/textures/surf-canvas.webp",
    "kind": "mask",
    "mean": [
      0.5221,
      0.5221,
      0.5221
    ],
    "bytes": 31724
  },
  "plaza": {
    "url": "/textures/plaza.webp",
    "kind": "decal",
    "bytes": 174794
  },
  "leaf-broad": {
    "url": "/textures/leaf-broad.webp",
    "kind": "tint",
    "bytes": 13410
  },
  "leaf-single": {
    "url": "/textures/leaf-single.webp",
    "kind": "tint",
    "bytes": 4896
  },
  "grass-card": {
    "url": "/textures/grass-card.webp",
    "kind": "tint",
    "bytes": 17566
  },
  "moon": {
    "url": "/textures/moon.webp",
    "kind": "sprite",
    "bytes": 15122
  },
  "conifer-atlas": {
    "url": "/textures/conifer-atlas.webp",
    "kind": "tint",
    "bytes": 78050,
    "cells": [
      "conifer-clump",
      "conifer-bough",
      "conifer-tufts",
      "conifer-crown"
    ]
  },
  "pond-atlas": {
    "url": "/textures/pond-atlas.webp",
    "kind": "sprite",
    "bytes": 111592,
    "cells": [
      "pond-lilies",
      "pond-reeds",
      "pond-iris",
      "pond-fern"
    ]
  }
} as const;

export type TextureName = keyof typeof TEXTURES;
