// Generated by scripts/build-textures.py — do not edit by hand.
// `mean` is the tile's average colour in linear space (used to keep the shader's palette).
export const TEXTURES = {
  "grass": {
    "url": "/textures/grass.webp",
    "kind": "tile",
    "mean": [
      0.2824,
      0.6015,
      0.0893
    ],
    "bytes": 53432
  },
  "dirt": {
    "url": "/textures/dirt.webp",
    "kind": "tile",
    "mean": [
      0.6824,
      0.4143,
      0.1677
    ],
    "bytes": 46562
  },
  "cobble": {
    "url": "/textures/cobble.webp",
    "kind": "tile",
    "mean": [
      0.7884,
      0.675,
      0.5213
    ],
    "bytes": 16410
  },
  "sand": {
    "url": "/textures/sand.webp",
    "kind": "tile",
    "mean": [
      0.8385,
      0.577,
      0.2566
    ],
    "bytes": 47078
  },
  "riverbed": {
    "url": "/textures/riverbed.webp",
    "kind": "tile",
    "mean": [
      0.2164,
      0.1561,
      0.0799
    ],
    "bytes": 55398
  },
  "rock": {
    "url": "/textures/rock.webp",
    "kind": "tile",
    "mean": [
      0.6494,
      0.3493,
      0.1658
    ],
    "bytes": 17700
  },
  "boulder": {
    "url": "/textures/boulder.webp",
    "kind": "mask",
    "mean": [
      0.4867,
      0.4867,
      0.4867
    ],
    "bytes": 32642
  },
  "water": {
    "url": "/textures/water.webp",
    "kind": "mask",
    "mean": [
      0.2065,
      0.2065,
      0.2065
    ],
    "bytes": 60404
  },
  "paint-grain": {
    "url": "/textures/paint-grain.webp",
    "kind": "mask",
    "mean": [
      0.5265,
      0.5265,
      0.5265
    ],
    "bytes": 32524
  },
  "surf-wood": {
    "url": "/textures/surf-wood.webp",
    "kind": "mask",
    "mean": [
      0.5349,
      0.5349,
      0.5349
    ],
    "bytes": 76614
  },
  "surf-shingle": {
    "url": "/textures/surf-shingle.webp",
    "kind": "mask",
    "mean": [
      0.7098,
      0.7098,
      0.7098
    ],
    "bytes": 42046
  },
  "surf-plaster": {
    "url": "/textures/surf-plaster.webp",
    "kind": "mask",
    "mean": [
      0.5066,
      0.5066,
      0.5066
    ],
    "bytes": 33086
  },
  "surf-stone": {
    "url": "/textures/surf-stone.webp",
    "kind": "mask",
    "mean": [
      0.7216,
      0.7216,
      0.7216
    ],
    "bytes": 49024
  },
  "surf-brick": {
    "url": "/textures/surf-brick.webp",
    "kind": "mask",
    "mean": [
      0.6652,
      0.6652,
      0.6652
    ],
    "bytes": 22576
  },
  "surf-metal": {
    "url": "/textures/surf-metal.webp",
    "kind": "mask",
    "mean": [
      0.3642,
      0.3642,
      0.3642
    ],
    "bytes": 26542
  },
  "surf-canvas": {
    "url": "/textures/surf-canvas.webp",
    "kind": "mask",
    "mean": [
      0.5221,
      0.5221,
      0.5221
    ],
    "bytes": 31724
  },
  "surf-bark": {
    "url": "/textures/surf-bark.webp",
    "kind": "mask",
    "mean": [
      0.6089,
      0.6089,
      0.6089
    ],
    "bytes": 29744
  },
  "plaza": {
    "url": "/textures/plaza.webp",
    "kind": "decal",
    "bytes": 174794
  },
  "leaf-broad": {
    "url": "/textures/leaf-broad.webp",
    "kind": "tint",
    "bytes": 13410
  },
  "leaf-single": {
    "url": "/textures/leaf-single.webp",
    "kind": "tint",
    "bytes": 4896
  },
  "moon": {
    "url": "/textures/moon.webp",
    "kind": "sprite",
    "bytes": 15122
  },
  "chopper-fur": {
    "url": "/textures/chopper-fur.webp",
    "kind": "mask",
    "mean": [
      0.5233,
      0.5233,
      0.5233
    ],
    "bytes": 32856
  },
  "picnic-mat": {
    "url": "/textures/picnic-mat.webp",
    "kind": "decal",
    "bytes": 13708
  },
  "conifer-atlas": {
    "url": "/textures/conifer-atlas.webp",
    "kind": "tint",
    "bytes": 78050,
    "cells": [
      "conifer-clump",
      "conifer-bough",
      "conifer-tufts",
      "conifer-crown"
    ]
  },
  "pond-atlas": {
    "url": "/textures/pond-atlas.webp",
    "kind": "sprite",
    "bytes": 111592,
    "cells": [
      "pond-lilies",
      "pond-reeds",
      "pond-iris",
      "pond-fern"
    ]
  },
  "cloud-atlas": {
    "url": "/textures/cloud-atlas.webp",
    "kind": "sprite",
    "bytes": 115836,
    "cells": [
      "cloud-a",
      "cloud-b",
      "cloud-c",
      "cloud-d"
    ],
    "rects": [
      [
        0.01953,
        0.52734,
        0.47949,
        0.97266
      ],
      [
        0.56934,
        0.51953,
        0.92969,
        0.98047
      ],
      [
        0.05664,
        0.01953,
        0.44238,
        0.48047
      ],
      [
        0.51953,
        0.15039,
        0.97949,
        0.34961
      ]
    ]
  },
  "cloud-normal": {
    "url": "/textures/cloud-normal.webp",
    "kind": "normal",
    "bytes": 13946
  },
  "tuft-atlas": {
    "url": "/textures/tuft-atlas.webp",
    "kind": "tint",
    "bytes": 82136,
    "cells": [
      "meadow-tuft-1",
      "meadow-tuft-2",
      "meadow-tuft-3",
      "meadow-tuft-4",
      "meadow-tuft-5",
      "meadow-tuft-6",
      "meadow-tuft-7",
      "meadow-tuft-8"
    ],
    "rects": [
      [
        0.0625,
        0.50195,
        0.1875,
        0.98633
      ],
      [
        0.25781,
        0.50195,
        0.49219,
        0.95703
      ],
      [
        0.5332,
        0.50195,
        0.71484,
        0.98633
      ],
      [
        0.77344,
        0.50195,
        0.97656,
        0.98633
      ],
      [
        0.0293,
        0.00195,
        0.21875,
        0.48633
      ],
      [
        0.30859,
        0.00195,
        0.44141,
        0.48633
      ],
      [
        0.51953,
        0.00195,
        0.72852,
        0.48633
      ],
      [
        0.79883,
        0.00195,
        0.95117,
        0.48633
      ]
    ]
  },
  "grass-normal": {
    "url": "/textures/grass-normal.webp",
    "kind": "normal",
    "bytes": 17456
  },
  "cobble-normal": {
    "url": "/textures/cobble-normal.webp",
    "kind": "normal",
    "bytes": 8216
  }
} as const;

export type TextureName = keyof typeof TEXTURES;
