"""Build the background music from the owner's source tracks in assets-src/audio/music/.

Each track is loudness-normalised (EBU R128, two-pass loudnorm to -16 LUFS, -1.5 dBTP) so the two
play at the same level, then encoded as a 96 kbps stereo MP3 (it streams and plays quietly under
the ambience, so a modest bitrate is plenty). Writes:
  public/audio/music-<n>.mp3
  src/game/audio/musicManifest.ts   (URLs, durations, sizes)

Requires Python 3.10+ and ffmpeg on PATH. Outputs are committed, so only asset authors need it:
    python scripts/build-music.py
"""
from __future__ import annotations

import json
import re
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "assets-src" / "audio" / "music"
OUT = ROOT / "public" / "audio"
MANIFEST = ROOT / "src" / "game" / "audio" / "musicManifest.ts"
# playlist order: source file -> output name
TRACKS = [("mossy-window-nook-v1.mp3", "music-1.mp3"), ("mossy-window-nook-v2.mp3", "music-2.mp3")]
LUFS, PEAK, LRA = -16.0, -1.5, 11.0


def measure(src: Path) -> dict:
    """First loudnorm pass: the source's measured loudness, for an accurate (linear) second pass."""
    out = subprocess.run(
        ["ffmpeg", "-hide_banner", "-nostats", "-i", str(src), "-af", f"loudnorm=I={LUFS}:TP={PEAK}:LRA={LRA}:print_format=json", "-f", "null", "-"],
        capture_output=True, text=True, check=True,
    ).stderr
    return json.loads(re.search(r"\{[^{}]*\"input_i\"[^{}]*\}", out, re.S).group(0))


def duration(p: Path) -> float:
    out = subprocess.run(["ffprobe", "-v", "error", "-show_entries", "format=duration", "-of", "default=nw=1:nk=1", str(p)], capture_output=True, text=True, check=True).stdout
    return round(float(out.strip()), 2)


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    entries = []
    for src_name, out_name in TRACKS:
        src = SRC / src_name
        m = measure(src)
        af = (
            f"loudnorm=I={LUFS}:TP={PEAK}:LRA={LRA}:measured_I={m['input_i']}:measured_TP={m['input_tp']}:"
            f"measured_LRA={m['input_lra']}:measured_thresh={m['input_thresh']}:offset={m['target_offset']}:linear=true,"
            "aresample=44100"
        )
        dst = OUT / out_name
        subprocess.run(
            ["ffmpeg", "-hide_banner", "-loglevel", "error", "-y", "-i", str(src), "-af", af, "-ac", "2", "-ar", "44100", "-c:a", "libmp3lame", "-b:a", "96k", "-map_metadata", "-1", str(dst)],
            check=True,
        )
        size = dst.stat().st_size
        entries.append({"url": f"/audio/{out_name}", "seconds": duration(dst), "bytes": size})
        print(f"{out_name}: {entries[-1]['seconds']} s, {size / 1024:.0f} KB (source {m['input_i']} LUFS)")
    MANIFEST.write_text(
        "// Generated by scripts/build-music.py — do not edit by hand.\n"
        "// Background music playlist (played in order, looping), streamed after Start with sound on.\n"
        f"export const MUSIC = {json.dumps(entries, indent=2)} as const;\n",
        encoding="utf-8",
    )


if __name__ == "__main__":
    main()
