"""
The site's fonts, cut to what the site uses (docs: documentation/site-ui/mobile-audit.md §3.1).

The Google Fonts come from the pinned Fontsource packages (@fontsource-variable/*, latin subset). This
pins the variable axes the site never varies, which halves Fraunces on a phone:
  - Fraunces keeps opsz (optical size follows the size) and wght; SOFT and WONK are pinned from the
    tokens (axes.display for the roman, axes.display-italic for the italic);
  - Newsreader keeps wght from the regular to the semibold weight token;
  - Figtree is copied as it is.
It writes src/site/assets/fonts/*.woff2 and src/site/styles/fonts.css (@font-face). Never hand-edit
either: change the tokens or this script and run `python scripts/build-site-fonts.py`.
`--check` fails if the outputs are out of date.
"""
import io
import json
import re
import sys
from pathlib import Path

from fontTools.ttLib import TTFont
from fontTools.varLib.instancer import instantiateVariableFont

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / 'node_modules' / '@fontsource-variable'
OUT = ROOT / 'src' / 'site' / 'assets' / 'fonts'
CSS = ROOT / 'src' / 'site' / 'styles' / 'fonts.css'
TOKENS = json.loads((ROOT / 'src' / 'site' / 'design' / 'tokens.json').read_text(encoding='utf-8'))

# the latin subset's range, as Fontsource declares it
LATIN = 'U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD'


def axes(name):
    """'SOFT' 100, 'WONK' 0 -> {'SOFT': 100, 'WONK': 0}"""
    v = TOKENS['axes'][name]['$value']
    return {m[0]: float(m[1]) for m in re.findall(r"'(\w{4})'\s+([\d.]+)", v)}


def weight(name):
    return TOKENS['weight'][name]['$value']


FACES = [
    # family, style, source, limits, output, css weight range
    ('Fraunces', 'normal', 'fraunces/files/fraunces-latin-full-normal.woff2', axes('display'), 'fraunces-roman.woff2', '100 900'),
    ('Fraunces', 'italic', 'fraunces/files/fraunces-latin-full-italic.woff2', axes('display-italic'), 'fraunces-italic.woff2', '100 900'),
    ('Newsreader', 'normal', 'newsreader/files/newsreader-latin-wght-normal.woff2', {'wght': (weight('regular'), weight('regular'), weight('semibold'))}, 'newsreader-roman.woff2', f"{weight('regular')} {weight('semibold')}"),
    ('Newsreader', 'italic', 'newsreader/files/newsreader-latin-wght-italic.woff2', {'wght': (weight('regular'), weight('regular'), weight('semibold'))}, 'newsreader-italic.woff2', f"{weight('regular')} {weight('semibold')}"),
    ('Figtree', 'normal', 'figtree/files/figtree-latin-wght-normal.woff2', None, 'figtree-roman.woff2', '300 900'),
]


def build(face):
    _, _, src, limits, _, _ = face
    # no timestamp: the same input gives the same bytes (so --check can compare)
    font = TTFont(SRC / src, recalcTimestamp=False)
    if limits:
        font = instantiateVariableFont(font, limits)
    font.flavor = 'woff2'
    buf = io.BytesIO()
    font.save(buf)
    return buf.getvalue()


def css():
    lines = [
        '/* GENERATED by scripts/build-site-fonts.py from the Fontsource packages and the tokens. Do not edit.',
        ' * The site\'s three faces, latin only, with the axes the site never varies pinned (mobile-audit.md §3.1). */',
        '',
    ]
    for family, style, _, _, out, weights in FACES:
        lines += [
            '@font-face {',
            f"  font-family: '{family}';",
            f'  font-style: {style};',
            '  font-display: swap;',
            f'  font-weight: {weights};',
            f"  src: url('../assets/fonts/{out}') format('woff2');",
            f'  unicode-range: {LATIN};',
            '}',
            '',
        ]
    return '\n'.join(lines)


def main():
    check = '--check' in sys.argv
    stale = []
    OUT.mkdir(parents=True, exist_ok=True)
    for face in FACES:
        data = build(face)
        path = OUT / face[4]
        if check:
            if not path.exists() or path.read_bytes() != data:
                stale.append(str(path))
        else:
            path.write_bytes(data)
            print(f'{face[4]:24} {len(data) // 1024:4} KB')
    text = css()
    if check:
        if not CSS.exists() or CSS.read_text(encoding='utf-8').replace('\r\n', '\n') != text:
            stale.append(str(CSS))
        if stale:
            print('Out of date: ' + ', '.join(stale) + '. Run python scripts/build-site-fonts.py')
            sys.exit(1)
        print('site fonts up to date')
    else:
        CSS.write_text(text, encoding='utf-8', newline='\n')


if __name__ == '__main__':
    main()
