import { existsSync, readFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { describe, expect, it } from 'vitest';

// the game's cursors (design system §4): generated by scripts/build-cursors.mjs into src/styles/cursors.css
const ROOT = join(__dirname, '../..');
const CSS = join(ROOT, 'src/styles/cursors.css');
const css = readFileSync(CSS, 'utf8');
const pngSize = (f: string) => {
  const b = readFileSync(f);
  return [b.readUInt32BE(16), b.readUInt32BE(20)];
};

describe('cursors', () => {
  const rules = [...css.matchAll(/\/\* ([\w-]+): hotspot (\d+) (\d+) \*\/\n([^{]+)\{([^}]+)\}/g)].map((m) => ({ name: m[1], hx: +m[2], hy: +m[3], selectors: m[4], body: m[5] }));

  it('are generated, with every state the game shows', () => {
    expect(css).toMatch(/Generated by scripts\/build-cursors\.mjs/);
    expect(rules.map((r) => r.name).sort()).toEqual(['arrow', 'ew-resize', 'grab', 'grabbing', 'not-allowed', 'pointer', 'walk']);
    expect(readFileSync(join(ROOT, 'src/styles/global.css'), 'utf8')).toMatch(/@import '\.\/cursors\.css';\s*$/);
  });

  it('each is a 32 px image with a 64 px one for sharp screens, a hotspot inside it and a system fallback', () => {
    for (const r of rules) {
      const urls = [...r.body.matchAll(/url\('([^']+)'\)/g)].map((m) => resolve(dirname(CSS), m[1]));
      expect(urls.length, r.name).toBe(3);
      for (const u of urls) expect(existsSync(u), u).toBe(true);
      expect(pngSize(urls[0])).toEqual([32, 32]);
      expect(pngSize(urls[2])).toEqual([64, 64]);
      expect(r.hx).toBeLessThan(32);
      expect(r.hy).toBeLessThan(32);
      // a plain url() first (browsers without image-set cursors), then image-set, each ending in a keyword
      expect(r.body).toMatch(/cursor: url\([^)]+\) \d+ \d+, [\w-]+;\s*cursor: image-set\(/);
    }
  });

  it('only the game uses them, and over the ground the walk cursor wins unless a landmark or a drag says otherwise', () => {
    for (const r of rules) for (const s of r.selectors.split(',')) expect(s.trim()).toMatch(/^(body)?\.play\b/);
    const at = (name: string) => rules.findIndex((r) => r.name === name);
    // the landmark's pointer out-ranks the walk cursor (more specific), and the drag's grabbing comes last
    expect(rules[at('pointer')].selectors).toContain('[data-cursor="walk"][data-hover="landmark"]');
    expect(at('grabbing')).toBeGreaterThan(at('walk'));
    expect(rules[at('grabbing')].selectors).toContain('.dragging[data-hover]');
  });
});
